Traceback (most recent call last):
  File "C:\Users\rob_t\anaconda3\envs\steam_nlp\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\rob_t\anaconda3\envs\steam_nlp\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\rob_t\anaconda3\envs\steam_nlp\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\rob_t\anaconda3\envs\steam_nlp\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\rob_t\anaconda3\envs\steam_nlp\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\rob_t\anaconda3\envs\steam_nlp\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\rob_t\anaconda3\envs\steam_nlp\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\rob_t\anaconda3\envs\steam_nlp\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd

# quantify missing
display(pd.DataFrame({'Missing':len(df.loc[df['review_text'].str.split().str.len()<1]),
        'Present':len(df.loc[df['review_text'].str.split().str.len()>0]),
       'Total':len(df)},index = ['Review Text']))
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [1][0m, in [0;36m<cell line: 4>[1;34m()[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m      3[0m [38;5;66;03m# quantify missing[39;00m
[1;32m----> 4[0m display(pd[38;5;241m.[39mDataFrame({[38;5;124m'[39m[38;5;124mMissing[39m[38;5;124m'[39m:[38;5;28mlen[39m([43mdf[49m[38;5;241m.[39mloc[df[[38;5;124m'[39m[38;5;124mreview_text[39m[38;5;124m'[39m][38;5;241m.[39mstr[38;5;241m.[39msplit()[38;5;241m.[39mstr[38;5;241m.[39mlen()[38;5;241m<[39m[38;5;241m1[39m]),
[0;32m      5[0m         [38;5;124m'[39m[38;5;124mPresent[39m[38;5;124m'[39m:[38;5;28mlen[39m(df[38;5;241m.[39mloc[df[[38;5;124m'[39m[38;5;124mreview_text[39m[38;5;124m'[39m][38;5;241m.[39mstr[38;5;241m.[39msplit()[38;5;241m.[39mstr[38;5;241m.[39mlen()[38;5;241m>[39m[38;5;241m0[39m]),
[0;32m      6[0m        [38;5;124m'[39m[38;5;124mTotal[39m[38;5;124m'[39m:[38;5;28mlen[39m(df)},index [38;5;241m=[39m [[38;5;124m'[39m[38;5;124mReview Text[39m[38;5;124m'[39m]))

[1;31mNameError[0m: name 'df' is not defined
NameError: name 'df' is not defined

